### ISSUE TITLE
Unknown extension: de.systopia.remotetools

### ISSUE THREAD

**Issue by smch** [systopia/de.systopia.eventcheckin#1]
Hi there, I'd like to try this extension but I get this error when I enable it: 

CiviCRM_API3_Exception: "Unknown extension: de.systopia.remotetools"

**Comment by bjendres** [comment]
Well, yes. As listed in the required extensions, you'd have to install https://github.com/systopia/de.systopia.remotetools as well.

When both extensions eventually are listed in the extension directory, and flagged for automatic distribution, this would be done automatically.

**Comment by smch** [comment]
Thanks for the quick reply! That link gives me a 404.

**Comment by bjendres** [comment]
> Thanks for the quick reply! That link gives me a 404.

Sorry - my bad. That repository was still marked private. m(

I changed the settings, you should have access now. Let me know if it worked for you.
